In [198]:
import pandas as pd 
import pandasql as ps 
import numpy as np
import seaborn as sns

In [199]:
data=pd.read_csv(r"C:\Users\BrunoNad\Downloads\Chicago_Public_Schools_-_Progress_Report_Cards_(2011-2012)_20251016.csv")
data.head()

,School ID,Name of School,"Elementary, Middle, or High School",Street Address,City,State,ZIP Code,Phone Number,Link,Network Manager,...,RCDTS Code,X_COORDINATE,Y_COORDINATE,Latitude,Longitude,Community Area Number,Community Area Name,Ward,Police District,Location
0,610038,Abraham Lincoln Elementary School,ES,615 W Kemper Pl,Chicago,IL,60614,(773) 534-5720,http://schoolreports.cps.edu/SchoolProgressRep...,Fullerton Elementary Network,...,150000000000000,1171699.458,1915829.428,41.924497,-87.644522,7,LINCOLN PARK,43,18,"(41.92449696, -87.64452163)"
1,610281,Adam Clayton Powell Paideia Community Academy ...,ES,7511 S South Shore Dr,Chicago,IL,60649,(773) 535-6650,http://schoolreports.cps.edu/SchoolProgressRep...,Skyway Elementary Network,...,150000000000000,1196129.985,1856209.466,41.760324,-87.556736,43,SOUTH SHORE,7,4,"(41.76032435, -87.55673627)"
2,610185,Adlai E Stevenson Elementary School,ES,8010 S Kostner Ave,Chicago,IL,60652,(773) 535-2280,http://schoolreports.cps.edu/SchoolProgressRep...,Midway Elementary Network,...,150000000000000,1148427.165,1851012.215,41.747111,-87.731702,70,ASHBURN,13,8,"(41.74711093, -87.73170248)"
3,609993,Agustin Lara Elementary Academy,ES,4619 S Wolcott Ave,Chicago,IL,60609,(773) 535-4389,http://schoolreports.cps.edu/SchoolProgressRep...,Pershing Elementary Network,...,150000000000000,1164504.290,1873959.199,41.809757,-87.672145,61,NEW CITY,20,9,"(41.8097569, -87.6721446)"
4,610513,Air Force Academy High School,HS,3630 S Wells St,Chicago,IL,60609,(773) 535-1590,http://schoolreports.cps.edu/SchoolProgressRep...,Southwest Side High School Network,...,150000000000000,1175177.622,1880745.126,41.828146,-87.632794,34,ARMOUR SQUARE,11,9,"(41.82814609, -87.63279369)"

In [200]:
nan_columns=[i for i in data.columns if (data[i].isnull().sum())>0]
nan_columns

['Link ',
 'Safety Score',
 'Environment Score',
 'Instruction Score',
 'Average Student Attendance',
 'ISAT Exceeding Math %',
 'ISAT Exceeding Reading % ',
 'ISAT Value Add Math',
 'ISAT Value Add Read']

In [201]:
data.columns

Index(['School ID', 'Name of School', 'Elementary, Middle, or High School',
       'Street Address', 'City', 'State', 'ZIP Code', 'Phone Number', 'Link ',
       'Network Manager', 'Collaborative Name',
       'Adequate Yearly Progress Made? ', 'Track Schedule',
       'CPS Performance Policy Status', 'CPS Performance Policy Level',
       'Healthy Schools Certified?', 'Safety Icon ', 'Safety Score',
       'Family Involvement Icon', 'Family Involvement Score',
       'Environment Icon ', 'Environment Score', 'Instruction Icon ',
       'Instruction Score', 'Leaders Icon ', 'Leaders Score ',
       'Teachers Icon ', 'Teachers Score', 'Parent Engagement Icon ',
       'Parent Engagement Score', 'Parent Environment Icon',
       'Parent Environment Score', 'Average Student Attendance',
       'Rate of Misconducts (per 100 students) ', 'Average Teacher Attendance',
       'Individualized Education Program Compliance Rate ', 'Pk-2 Literacy %',
       'Pk-2 Math %', 'Gr3-5 Grade Level Math %', 'Gr3-5 Grade Level Read % ',
       'Gr3-5 Keep Pace Read %', 'Gr3-5 Keep Pace Math %',
       'Gr6-8 Grade Level Math %', 'Gr6-8 Grade Level Read %',
       'Gr6-8 Keep Pace Math%', 'Gr6-8 Keep Pace Read %',
       'Gr-8 Explore Math %', 'Gr-8 Explore Read %', 'ISAT Exceeding Math %',
       'ISAT Exceeding Reading % ', 'ISAT Value Add Math',
       'ISAT Value Add Read', 'ISAT Value Add Color Math',
       'ISAT Value Add Color Read', 'Students Taking  Algebra %',
       'Students Passing  Algebra %', '9th Grade EXPLORE (2009) ',
       '9th Grade EXPLORE (2010) ', '10th Grade PLAN (2009) ',
       '10th Grade PLAN (2010) ', 'Net Change EXPLORE and PLAN',
       '11th Grade Average ACT (2011) ', 'Net Change PLAN and ACT',
       'College Eligibility %', 'Graduation Rate %',
       'College Enrollment Rate %', 'College Enrollment (number of students) ',
       'General Services Route ', 'Freshman on Track Rate %', 'RCDTS Code',
       'X_COORDINATE', 'Y_COORDINATE', 'Latitude', 'Longitude',
       'Community Area Number', 'Community Area Name', 'Ward',
       'Police District', 'Location'],
      dtype='object')

In [202]:
# problem 1: how many elementary schools are in the dataset?
data.rename(columns={'Elementary, Middle, or High School':'Elementary_Middle_or_High_school'},inplace=True)
ps.sqldf("SELECT COUNT(*) FROM data WHERE  (Elementary_Middle_or_High_school)='ES'")

   COUNT(*)
0       462

In [203]:
# problem 2: what is the highest safety score?
data.rename(columns={'Safety Score':'Safety_Score'},inplace=True)
ps.sqldf("SELECT MAX(Safety_Score) FROM data")

   MAX(Safety_Score)
0               99.0

In [204]:
data.columns

Index(['School ID', 'Name of School', 'Elementary_Middle_or_High_school',
       'Street Address', 'City', 'State', 'ZIP Code', 'Phone Number', 'Link ',
       'Network Manager', 'Collaborative Name',
       'Adequate Yearly Progress Made? ', 'Track Schedule',
       'CPS Performance Policy Status', 'CPS Performance Policy Level',
       'Healthy Schools Certified?', 'Safety Icon ', 'Safety_Score',
       'Family Involvement Icon', 'Family Involvement Score',
       'Environment Icon ', 'Environment Score', 'Instruction Icon ',
       'Instruction Score', 'Leaders Icon ', 'Leaders Score ',
       'Teachers Icon ', 'Teachers Score', 'Parent Engagement Icon ',
       'Parent Engagement Score', 'Parent Environment Icon',
       'Parent Environment Score', 'Average Student Attendance',
       'Rate of Misconducts (per 100 students) ', 'Average Teacher Attendance',
       'Individualized Education Program Compliance Rate ', 'Pk-2 Literacy %',
       'Pk-2 Math %', 'Gr3-5 Grade Level Math %', 'Gr3-5 Grade Level Read % ',
       'Gr3-5 Keep Pace Read %', 'Gr3-5 Keep Pace Math %',
       'Gr6-8 Grade Level Math %', 'Gr6-8 Grade Level Read %',
       'Gr6-8 Keep Pace Math%', 'Gr6-8 Keep Pace Read %',
       'Gr-8 Explore Math %', 'Gr-8 Explore Read %', 'ISAT Exceeding Math %',
       'ISAT Exceeding Reading % ', 'ISAT Value Add Math',
       'ISAT Value Add Read', 'ISAT Value Add Color Math',
       'ISAT Value Add Color Read', 'Students Taking  Algebra %',
       'Students Passing  Algebra %', '9th Grade EXPLORE (2009) ',
       '9th Grade EXPLORE (2010) ', '10th Grade PLAN (2009) ',
       '10th Grade PLAN (2010) ', 'Net Change EXPLORE and PLAN',
       '11th Grade Average ACT (2011) ', 'Net Change PLAN and ACT',
       'College Eligibility %', 'Graduation Rate %',
       'College Enrollment Rate %', 'College Enrollment (number of students) ',
       'General Services Route ', 'Freshman on Track Rate %', 'RCDTS Code',
       'X_COORDINATE', 'Y_COORDINATE', 'Latitude', 'Longitude',
       'Community Area Number', 'Community Area Name', 'Ward',
       'Police District', 'Location'],
      dtype='object')

In [205]:
# problem 3: which schools have highest safety score?
data.rename(columns={'Name of School':'Name_of_School'},inplace=True)
ps.sqldf("SELECT Name_of_School FROM data WHERE Safety_Score=(SELECT MAX(Safety_Score) FROM data)")

                                      Name_of_School
0                  Abraham Lincoln Elementary School
1            Alexander Graham Bell Elementary School
2       Annie Keller Elementary Gifted Magnet School
3                Augustus H Burley Elementary School
4        Edgar Allan Poe Elementary Classical School
5                        Edgebrook Elementary School
6                   Ellen Mitchell Elementary School
7         James E McDade Elementary Classical School
8                   James G Blaine Elementary School
9                LaSalle Elementary Language Academy
10  Mary E Courtenay Elementary Language Arts Center
11         Northside College Preparatory High School
12             Northside Learning Center High School
13                    Norwood Park Elementary School
14                     Oriole Park Elementary School
15                       Sauganash Elementary School
16       Stephen Decatur Classical Elementary School
17                          Talman Elementary School
18                        Wildwood Elementary School

In [206]:
data['Average Student Attendance']

0      96.0%
1      95.6%
2      95.7%
3      95.5%
4      93.3%
       ...
561    91.2%
562    80.0%
563    95.2%
564    93.9%
565    91.6%
Name: Average Student Attendance, Length: 566, dtype: object

In [207]:
data.columns

Index(['School ID', 'Name_of_School', 'Elementary_Middle_or_High_school',
       'Street Address', 'City', 'State', 'ZIP Code', 'Phone Number', 'Link ',
       'Network Manager', 'Collaborative Name',
       'Adequate Yearly Progress Made? ', 'Track Schedule',
       'CPS Performance Policy Status', 'CPS Performance Policy Level',
       'Healthy Schools Certified?', 'Safety Icon ', 'Safety_Score',
       'Family Involvement Icon', 'Family Involvement Score',
       'Environment Icon ', 'Environment Score', 'Instruction Icon ',
       'Instruction Score', 'Leaders Icon ', 'Leaders Score ',
       'Teachers Icon ', 'Teachers Score', 'Parent Engagement Icon ',
       'Parent Engagement Score', 'Parent Environment Icon',
       'Parent Environment Score', 'Average Student Attendance',
       'Rate of Misconducts (per 100 students) ', 'Average Teacher Attendance',
       'Individualized Education Program Compliance Rate ', 'Pk-2 Literacy %',
       'Pk-2 Math %', 'Gr3-5 Grade Level Math %', 'Gr3-5 Grade Level Read % ',
       'Gr3-5 Keep Pace Read %', 'Gr3-5 Keep Pace Math %',
       'Gr6-8 Grade Level Math %', 'Gr6-8 Grade Level Read %',
       'Gr6-8 Keep Pace Math%', 'Gr6-8 Keep Pace Read %',
       'Gr-8 Explore Math %', 'Gr-8 Explore Read %', 'ISAT Exceeding Math %',
       'ISAT Exceeding Reading % ', 'ISAT Value Add Math',
       'ISAT Value Add Read', 'ISAT Value Add Color Math',
       'ISAT Value Add Color Read', 'Students Taking  Algebra %',
       'Students Passing  Algebra %', '9th Grade EXPLORE (2009) ',
       '9th Grade EXPLORE (2010) ', '10th Grade PLAN (2009) ',
       '10th Grade PLAN (2010) ', 'Net Change EXPLORE and PLAN',
       '11th Grade Average ACT (2011) ', 'Net Change PLAN and ACT',
       'College Eligibility %', 'Graduation Rate %',
       'College Enrollment Rate %', 'College Enrollment (number of students) ',
       'General Services Route ', 'Freshman on Track Rate %', 'RCDTS Code',
       'X_COORDINATE', 'Y_COORDINATE', 'Latitude', 'Longitude',
       'Community Area Number', 'Community Area Name', 'Ward',
       'Police District', 'Location'],
      dtype='object')

In [208]:
data['Average Student Attendance']=data['Average Student Attendance'].dropna()
data['Average Student Attendance'].isnull().sum()

np.int64(1)

In [209]:
# index podatka koji je nan u data['Average Student Attendance']
data['Average Student Attendance'].index[data['Average Student Attendance'].isna()]

Index([511], dtype='int64')

In [210]:
data['Average Student Attendance'][511]

nan

In [211]:
# problem 4: What are the top 10 schools with the highest "Average Student Attendance"?

data.rename(columns={'Average Student Attendance':'Average_Student_Attendance'},inplace=True)
data['Average_Student_Attendance'].drop(index=511,inplace=True)
ps.sqldf("SELECT Name_of_School FROM data ORDER BY Average_Student_Attendance DESC LIMIT 10")

                                  Name_of_School
0          John Charles Haines Elementary School
1                   James Ward Elementary School
2    Edgar Allan Poe Elementary Classical School
3  Orozco Fine Arts & Sciences Elementary School
4                Rachel Carson Elementary School
5   Annie Keller Elementary Gifted Magnet School
6     Andrew Jackson Elementary Language Academy
7       Lenart Elementary Regional Gifted Center
8                        Disney II Magnet School
9     John H Vanderpoel Elementary Magnet School

In [212]:
data['Average_Student_Attendance']

0      96.0%
1      95.6%
2      95.7%
3      95.5%
4      93.3%
       ...
561    91.2%
562    80.0%
563    95.2%
564    93.9%
565    91.6%
Name: Average_Student_Attendance, Length: 566, dtype: object

In [213]:
# problem 5: Retrieve the list of 5 Schools with the lowest Average Student Attendance sorted in ascending order based on attendance

ps.sqldf("SELECT Name_of_School FROM data ORDER BY Average_Student_Attendance ASC LIMIT 5")

                                      Name_of_School
0              Velma F Thomas Early Childhood Center
1  Richard T Crane Technical Preparatory High School
2       Barbara Vick Early Childhood & Family Center
3                                  Dyett High School
4               Wendell Phillips Academy High School

In [214]:
# problem 6: Now remove the '%' sign from the above result set for Average Student Attendance column

ps.sqldf("SELECT Name_of_School, REPLACE (Average_Student_Attendance,'%','') FROM data ORDER BY Average_Student_Attendance ASC LIMIT 5")

,Name_of_School,"REPLACE (Average_Student_Attendance,'%','')"
0,Velma F Thomas Early Childhood Center,None
1,Richard T Crane Technical Preparatory High School,57.9
2,Barbara Vick Early Childhood & Family Center,60.9
3,Dyett High School,62.5
4,Wendell Phillips Academy High School,63.0

In [215]:
data['Average_Student_Attendance']

0      96.0%
1      95.6%
2      95.7%
3      95.5%
4      93.3%
       ...
561    91.2%
562    80.0%
563    95.2%
564    93.9%
565    91.6%
Name: Average_Student_Attendance, Length: 566, dtype: object

In [216]:
# problem 7: Which Schools have Average Student Attendance lower than 70%?

ps.sqldf("SELECT Name_of_School,CAST(Average_Student_Attendance AS DOUBLE)/100 FROM data WHERE CAST(Average_Student_Attendance AS DOUBLE)/100<0.7")

,Name_of_School,CAST(Average_Student_Attendance AS DOUBLE)/100
0,Barbara Vick Early Childhood & Family Center,0.609
1,Chicago Vocational Career Academy High School,0.688
2,Dyett High School,0.625
3,Manley Career Academy High School,0.668
4,Orr Academy High School,0.663
5,Richard T Crane Technical Preparatory High School,0.579
6,Roberto Clemente Community Academy High School,0.696
7,Wendell Phillips Academy High School,0.630

In [217]:
data['Community Area Name']

0         LINCOLN PARK
1          SOUTH SHORE
2              ASHBURN
3             NEW CITY
4        ARMOUR SQUARE
            ...
561    WASHINGTON PARK
562     NEAR WEST SIDE
563       LOGAN SQUARE
564           WOODLAWN
565     SOUTH LAWNDALE
Name: Community Area Name, Length: 566, dtype: object

In [218]:
data['College Enrollment (number of students) ']

0        813
1        521
2      1,324
3        556
4        302
       ...
561      371
562      100
563      748
564      238
565      382
Name: College Enrollment (number of students) , Length: 566, dtype: object

In [219]:
# problem 8: Get the total College Enrollment for each Community Area
data.rename(columns={'Community Area Name':'Community_Area_Name','College Enrollment (number of students) ':'College_Enrollment_number_of_students'},inplace=True)
ps.sqldf("SELECT Community_Area_Name,SUM(College_Enrollment_number_of_students) AS Total_College_Enrollment FROM data GROUP BY Community_Area_Name")

   Community_Area_Name  Total_College_Enrollment
0          ALBANY PARK                    1817.0
1       ARCHER HEIGHTS                       4.0
2        ARMOUR SQUARE                    1458.0
3              ASHBURN                    2474.0
4       AUBURN GRESHAM                    4175.0
..                 ...                       ...
72           WEST LAWN                    2536.0
73        WEST PULLMAN                    3240.0
74          WEST RIDGE                    3895.0
75           WEST TOWN                    8414.0
76            WOODLAWN                    2689.0

[77 rows x 2 columns]

In [220]:
# problem 9: Get the 5 Community Areas with the least total College Enrollment sorted in ascending order
ps.sqldf("SELECT Community_Area_Name,SUM(College_Enrollment_number_of_students) AS Total_College_Enrollment FROM data GROUP BY Community_Area_Name ORDER BY Total_College_Enrollment ASC LIMIT 5")

  Community_Area_Name  Total_College_Enrollment
0           MONTCLARE                       1.0
1      ARCHER HEIGHTS                       4.0
2             OAKLAND                     140.0
3         FULLER PARK                     531.0
4            BURNSIDE                     549.0

In [221]:
# problem 10: List 5 schools with lowest safety score.
l=list(data['Safety_Score'].index[data['Safety_Score'].isna()])
data['Safety_Score']=data['Safety_Score'].drop(index=l)
ps.sqldf("SELECT Name_of_School,Safety_Score FROM data ORDER BY Safety_Score ASC LIMIT 5")

                                 Name_of_School Safety_Score
0            Ariel Elementary Community Academy         None
1               Arthur R Ashe Elementary School         None
2  Barbara Vick Early Childhood & Family Center         None
3                  Blair Early Childhood Center         None
4           Cyrus H McCormick Elementary School         None

In [222]:
# uvoz nove tablice zbog problema 11 i 12
data1=pd.read_csv(r"C:\Users\BrunoNad\Downloads\jcxq-k9xf.csv")
data1

,ca,community_area_name,percent_of_housing_crowded,percent_households_below_poverty,percent_aged_16_unemployed,percent_aged_25_without_high_school_diploma,percent_aged_under_18_or_over_64,per_capita_income_,hardship_index
0,1.0,Rogers Park,7.7,23.6,8.7,18.2,27.5,23939,39.0
1,2.0,West Ridge,7.8,17.2,8.8,20.8,38.5,23040,46.0
2,3.0,Uptown,3.8,24.0,8.9,11.8,22.2,35787,20.0
3,4.0,Lincoln Square,3.4,10.9,8.2,13.4,25.5,37524,17.0
4,5.0,North Center,0.3,7.5,5.2,4.5,26.2,57123,6.0
...,...,...,...,...,...,...,...,...,...
73,74.0,Mount Greenwood,1.0,3.4,8.7,4.3,36.8,34381,16.0
74,75.0,Morgan Park,0.8,13.2,15.0,10.8,40.3,27149,30.0
75,76.0,O'Hare,3.6,15.4,7.1,10.9,30.3,25828,24.0
76,77.0,Edgewater,4.1,18.2,9.2,9.7,23.8,33385,19.0
77,NaN,CHICAGO,4.7,19.7,12.9,19.5,33.5,28202,NaN

In [223]:
data1=data1.dropna()
data1

,ca,community_area_name,percent_of_housing_crowded,percent_households_below_poverty,percent_aged_16_unemployed,percent_aged_25_without_high_school_diploma,percent_aged_under_18_or_over_64,per_capita_income_,hardship_index
0,1.0,Rogers Park,7.7,23.6,8.7,18.2,27.5,23939,39.0
1,2.0,West Ridge,7.8,17.2,8.8,20.8,38.5,23040,46.0
2,3.0,Uptown,3.8,24.0,8.9,11.8,22.2,35787,20.0
3,4.0,Lincoln Square,3.4,10.9,8.2,13.4,25.5,37524,17.0
4,5.0,North Center,0.3,7.5,5.2,4.5,26.2,57123,6.0
...,...,...,...,...,...,...,...,...,...
72,73.0,Washington Height,1.1,16.9,20.8,13.7,42.6,19713,48.0
73,74.0,Mount Greenwood,1.0,3.4,8.7,4.3,36.8,34381,16.0
74,75.0,Morgan Park,0.8,13.2,15.0,10.8,40.3,27149,30.0
75,76.0,O'Hare,3.6,15.4,7.1,10.9,30.3,25828,24.0
76,77.0,Edgewater,4.1,18.2,9.2,9.7,23.8,33385,19.0

In [224]:
data.rename(columns={'Community Area Number':'Community_Area_Number'},inplace=True)

In [227]:
data['College_Enrollment_number_of_students'] = pd.to_numeric(data['College_Enrollment_number_of_students'].str.replace(',', ''), errors='coerce')

In [228]:
data['College_Enrollment_number_of_students']

0       813
1       521
2      1324
3       556
4       302
       ...
561     371
562     100
563     748
564     238
565     382
Name: College_Enrollment_number_of_students, Length: 566, dtype: int64

In [236]:
# problem 11: Get the hardship index for the community area of the school which has College Enrollment of 4368

ps.sqldf("SELECT hardship_index FROM data1 JOIN data ON data1.ca=data.Community_Area_Number WHERE data.College_Enrollment_number_of_students=4368")

   hardship_index
0             6.0

In [237]:
# problem 12: Get the hardship index for the community area which has the highest value for College Enrollment

ps.sqldf("SELECT hardship_index FROM data1 JOIN data ON data1.ca=data.Community_Area_Number WHERE data.College_Enrollment_number_of_students=(SELECT MAX(College_Enrollment_number_of_students) FROM data)")

   hardship_index
0             6.0